### ISSUE TITLE
template plot.tpl not found

### ISSUE THREAD

**Issue by pfarndt** [plotly/plotlyhtmlexporter#6]
After a fresh install (from source or via pip) the template file `plot.tpl` is not found.

```
> jupyter nbconvert --to plotlyhtml  Plot.ipynb 
[NbConvertApp] Converting notebook Plot.ipynb to plotlyhtml
[NbConvertApp] Sanitizing text/html
[NbConvertApp] Sanitizing text/html
Traceback (most recent call last):
  File "/home/NN/jupyterlab/bin/jupyter-nbconvert", line 11, in <module>
    load_entry_point('nbconvert==5.3.1', 'console_scripts', 'jupyter-nbconvert')()
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 325, in start
    self.convert_notebooks()
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 493, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 464, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 393, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 174, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 192, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/exporters/html.py", line 85, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 280, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 311, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/nbconvert/preprocessors/sanitize.py", line 96, in preprocess_cell
    cell.outputs = self.sanitize_code_outputs(cell.outputs)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/plotlyhtmlexporter/preprocessors.py", line 52, in sanitize_code_outputs
    data['text/html'] = self.template().render(**context)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/plotlyhtmlexporter/preprocessors.py", line 26, in template
    return env.get_template(filename)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/NN/jupyterlab/lib/python3.6/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: plot.tpl
```

**Comment by mraxilus** [comment]
I'm getting this as well.

**Comment by PC-hope** [comment]
hi!
Unable to download html of ipynb file where I plotted graphs using plotly.
Wrote the following code in jupyter notebook:
!pip3 install plotlyhtmlexporter
import nbformat
nb = nbformat.read('2019HyDistIndexProject.ipynb', 4)
from plotlyhtmlexporter import PlotlyHTMLExporter
exp = PlotlyHTMLExporter()
body, resources = exp.from_notebook_node(nb)

but getting error- >plot.tpl

Please help!!
